name: platform
version: 3.0.0-nullsafety
description: A pluggable, mockable platform abstraction for Dart.
homepage: https://github.com/google/platform.dart

dev_dependencies:
  test: ^1.16.0-nullsafety.1

environment:
  sdk: '>=2.10.0-4.0.dev <3.0.0'
