name: platform
version: 3.0.0-nullsafety
description: A pluggable, mockable platform abstraction for Dart.
homepage: https://github.com/google/platform.dart

dev_dependencies:
  test: ^1.0.0

environment:
  sdk: '>=2.8.0 <3.0.0'
